### ISSUE TITLE
数据预请求

### ISSUE THREAD

**Issue by chenjun1011** [ice-lab/ice-next#101]
## 背景

在 useEffect 中发起数据请求的方式，请求时机过于滞后。

将页面的 `数据请求` 和 `Bundle 加载` 并行起来，可以有效提升页面的首屏时间。

## 现有社区方案

前置数据请求目前有几种实现思路。以下面的代码为例：

- loader 为数据请求逻辑
- useLoaderData 为数据的消费逻辑

```js
export const loader = async () => {
  return json([
    { id: "1", name: "Pants" },
    { id: "2", name: "Jacket" },
  ]);
};

export default function Products() {
  const products = useLoaderData();
  return (
    <div>
      <h1>Products</h1>
      {products.map((product) => (
        <div key={product.id}>{product.name}</div>
      ))}
    </div>
  );
}
```

在 Remix 中

- loader 部分的代码会被发布为一个单独的 api `api/products`
- 框架维护 页面 和 页面 api 的映射关系，根据这个映射关系发起数据请求

优势：
- 在 loader 中可以做请求的入参处理，返回结果的适配
- 这部分逻辑交给 api 处理，框架维护的请求映射关系简单

在 Umi  中

- 所有页面的 loader 代码会被构建到主 Bundle 中
- 由主 Bundle 根据映射关系，来执行响应的代码，发起请求

优势：

- 不依赖于 api 

局限：

- 页面数量一旦过多，主 Bundle 的体积也会随之增长
- 需要引入较多不相关页面的实现逻辑，比如 B 页面没有路由跳转逻辑，也需要引入这部分代码
- loader 内部的实现复杂度，会影响到各个页面

## 设计原则

- 对包体积的影响尽可能小
- 对其他页面的影响尽可能小
- 请求的时机能尽可能的提前
- 能进一步转换为静态配置，供容器消费（比如 PHA）

## 方案

在路由组件上，静态的声明页面的接口信息，示例：

```jsx
export default function About() {
  const data = useData();

  return (
    <>
      <h2>About Page</h2>
      <Link to="/">home</Link>
      <span className="mark">new</span>
    </>
  );
}

// export function getData() {
//   return new Promise((resolve) => {
//     setTimeout(() => {
//       resolve({
//         name: 'About',
//       });
//     }, 1 * 100);
//   });
// }

export const dataRequest = {
  type: 'fetch',
  url: 'https://example.com/id=${query.id}',
};
```

声明了这个字段的路由：
- 数据请求和资源会并行发起
- 路由组件中声明了的 getData 方法，在初始化时会被 ignore
- useData 获取的数据对应 dataRequest 的返回数据。

请求参数动态的情况下，可消费以下数据：
- query: query 对象，取 query 上对应的 value；如果不带属性，取 URL Query 整个字符串 (不带 ?)
- cookie: 取 cookie 对象上的值
- url:  当前页面的 url

如果上诉描述方式，无法满足业务述求（如需要对参数做二次处理），可以继续使用 getData 发起自定义的数据请求 

构建产物大致如下：

```html
<!-- 所有路由的 api 映射关系 -->
<script>window.__ICE_APP_CONTEXT__={dataRequests: {}}</script>
<!-- 依赖的公共库 -->
<script defer src="windvane.js"></script>
<script defer src="mtop.js"></script>
<!-- 数据请求的处理逻辑 -->
<script defer src="/request.js"></script>
<script defer src="/PagesLayout.js"></script>
<script defer src="/PagesIndex.js"></script>
<script defer src="/runtime.js"></script>
<script defer src="/main.js"></script>
```

request.js 需要做的事情大致包含：
- 首次进入，立即发起当前页面的数据请求
- 在 window 上暴露 getData 方法，供 main 获取请求结果，或在路由跳转时，发起下一个页面的数据请求
- 如果首次进入是 SSR，则不发起数据请求，直接返回 SSR 的数据结果
- 如果端侧有更前置的数据预请求，则调用端侧的方法获取数据

**Comment by ClarkXia** [comment]
需要补充下具体的实现方案

**Comment by chenjun1011** [comment]
插件化方式实现 request

**Comment by sorrycc** [comment]
> 页面数量一旦过多，主 Bundle 的体积也会随之增长
> 需要引入较多不相关页面的实现逻辑，比如 B 页面没有路由跳转逻辑，也需要引入这部分代码
> loader 内部的实现复杂度，会影响到各个页面

我的理解是。

1、client 的 loader 相对简单，通常就是调用请求库发个请求，所以除非非常大的项目，并不会对主 Bundle 的尺寸有很大的影响
2、如果需要，在 Umi 现有基础上增加 Code Splitting 其实并不复杂

**Comment by chenjun1011** [comment]
初步实现下来，发现用静态化的方式来描述请求信息，确实会带来一下额外的成本，比如：
- 给开发者带来的编码限制
- 开发成本的增加
  - 数据请求需要同时支持静态（dataRequest）和动态（getData）配置
  - Server 端也需要兼容这种配置化的请求方式
     - 在 client 端可以直接消费 window 下的数据，以及在 window 下暴露全局变量给 main 使用
     - 在 server 端，则需要兼容上述逻辑，是额外的成本
  - 参数解析成本

所以，还是先简单处理，直接构建 getData 进行预请求
