### ISSUE TITLE
嵌套路由

### ISSUE THREAD

**Issue by chenjun1011** [ice-lab/ice-next#104]
## 背景

一张页面可能由多个嵌套的 Layout 和页面主体内容组成

- Layout1
  - Layout2
    -  Page

示例：https://remix.run/docs/en/v1/guides/routing#what-is-nested-routing

为了让各个层级都能获取数据或配置页面信息，需要让 Layout 也能支持  getInitialData 和 getPageConfig

## 方案

```
import * as React from 'react';
import { Outlet, useInitialData } from 'ice';
import type { PageConfig } from '@ice/runtime/esm/types';

export default function RepoLayout() {
 // 消费 initialData，initIalData 对应当前组件的 getInitialData 返回值
  const data = useInitialData();

  return (
    <div>
      Repo Layout {data.name}
      <Outlet />
    </div>
  );
}

// 设置页面级的数据
export function getPageConfig(): PageConfig {
  return {
    title: 'Repo',
    meta: [
      {
        name: 'theme-color',
        content: '#000',
      },
    ],
    auth: ['admin'],
  };
}

// 请求数据
export function getInitialData() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        name: 'Repo',
      });
    }, 1 * 100);
  });
}
```

**Comment by imsobear** [comment]
getInitialData 跟 getPageData 哪个更好？getPageData 和 getPageConfig 是对应的

**Comment by imsobear** [comment]
- getPageData <-> usePageData
- getAppData <-> useAppData

**Comment by imsobear** [comment]
layout 支持页面相关能力之后，这块的概念需要再对齐下，目前有两个方案：

- page，页面，当前方案
- route，路由，Remix 方案

然后这个概念会牵扯到几个地方可能的改动

## 目录名之类的

这部分是强耦合上面的概念，因此跟着确定好的概念即可： 
  
相关的地方：pages 目录、pageWrappers、wrapperPageComponent

## 配置信息（metas/scripts/auth/...）

可以不耦合概念，也可以耦合概念

1. 不耦合概念，比如  getConfig 或者其他的
2. 耦合概念，比如 getPageConfig（当前方案）

## 数据获取

1. 不耦合概念，比如  loader/useLoaderData、getIntialData/useInitialData，不过这里要考虑 App 层面怎么区分，获取数据的 hooks 命名不能冲突
2. 耦合概念，比如 getPageData/usePageData

## 其他

> 优先级较低

数据获取和配置这块应用层面可能也需要对齐，数据获取这块现在能力有支持，但写法不一样，metas 之类的配置应用层面现在是没有的，未来可能需要。

**Comment by chenjun1011** [comment]
概念上：
- 倾向还是保留 page 的概念，一张 page 可以由多个 route 组件嵌套组合而成
- 疑问：pageWrappers、wrapperPageComponent 是应该包在 Layout 之外，还是最底层的 route 之外？

配置信息：

- 倾向于不耦合概念

数据获取
- 倾向不耦合概念 getIntialData/useInitialData
- getPageData/usePageData 容易误解为会 merge  layout 的数据在一起？

**Comment by imsobear** [comment]
结论：

- 概念上选择 page
- pages 目录、pageWrappers、wrapperPageComponent，wrapperPageComponent 增加参数来控制是否要包裹 layout
- 配置：getConfig
- 获取数据：getData/useData，App 级别：getData/useAppData

**Comment by chenjun1011** [comment]
是不是还有必要提供一个 useConfig，例如 pageWrapper 中需要使用 auth 数据
