### ISSUE TITLE
SSR 渲染函数返回值优化

### ISSUE THREAD

**Issue by chenjun1011** [ice-lab/ice-next#108]
## 背景

当前 SSR 的入口函数，返回值为 html 字符串，存在一些限制：
- 无法返回渲染状态，比如是 404 或 500
- 外部还需要其他函数，进行返回结果的二次处理
- 不利于后续 Suspence 方式，流式的返回渲染内容

## 方案

在 render 函数内部，send 渲染结果和状态

**Comment by ClarkXia** [comment]
关联 issue #133
