### ISSUE TITLE
工程配置文件编写规范

### ISSUE THREAD

**Issue by imsobear** [ice-lab/ice-next#111]
## 配置文件

- 默认会读取 `iceice.config.(mts|mjs|ts|js|cjs|json)`（需要结合 build-scripts 的设计再明确下这块） @maoxiaoke 
- 除了 json 以外，只支持 ES Module 模式加载运行（因为后续官方的插件都是 ES Module Only 的格式）

### TypeScript 类型（推荐）

ice.config.ts

```ts
import { defineConfig } from '@ice/app';

export default defineConfig({
  alias: {}
});
```

也可以直接 `export default {}` ，会丢失提示能力。

### JavaScript 类型

ice.config.js

```js
import { defineConfig } from '@ice/app';

export default defineConfig({
  alias: {}
});
```

> 需要验证编辑器自动提示能力

也可以直接 `export default {}` ，会丢失提示能力。

### JSON 类型

```json
{
  "alias": {}
}
```

不支持自动提示。

### 自定义

通过 `--config` 指定：

```bash
$ ice start --config build.config.ts
```

**Comment by maoxiaoke** [comment]
build-scripts 2.x 配置文件解析策略 rfc https://github.com/ice-lab/build-scripts/issues/98

**Comment by ClarkXia** [comment]
脚手架默认增加 `ice.config.mjs` 文件
