### ISSUE TITLE
插件发包时编译 runtime 代码

### ISSUE THREAD

**Issue by imsobear** [ice-lab/ice-next#116]
目前插件发布 npm 包时未编译 runtime 代码，client 端会全量编译，server 端是选择性编译了插件 runtime，server 端可能会引入幽灵依赖的问题，因此希望插件发包时编译 runtime，client 和 server 端都使用编译后的 runtime。这里理论上编译成 ES2017 即可。

**Comment by luhc228** [comment]
编译 runtime 能解决幽灵依赖的问题吗？不是很理解

**Comment by imsobear** [comment]
@luhc228 runtime 编译（主要是 jsx + ts）了的话，esbuild 那块就不需要编译插件 runtime 了，直接 import 就行，不存在幽灵依赖的问题，反之，esbuild 编译 runtime 会把 runtime 的代码打包到 server bundle 里，这里面可能就有 runtime 自身的依赖了（比如 icestore），但是项目并没有依赖 icestore，这时候就出现幽灵依赖的问题了。
