### ISSUE TITLE
getData 入参规则

### ISSUE THREAD

**Issue by chenjun1011** [ice-lab/ice-next#126]
评估 initialContext 需要包含哪些参数，如何保持同构

**Comment by chenjun1011** [comment]
参考 next.js 的，context 可以包含以下内容：

- pathname - Current route. That is the path of the page in /pages
- query - Query string section of URL parsed as an object
- req - [HTTP request object](https://nodejs.org/api/http.html#http_class_http_incomingmessage) (server only)
- res - [HTTP response object](https://nodejs.org/api/http.html#http_class_http_serverresponse) (server only)

next.js https://nextjs.org/docs/api-reference/data-fetching/get-initial-props#context-object
remix https://remix.run/docs/en/v1/api/conventions#loader-params

另外，建议 initialContext 改成 requestContext，语义更明确点

@imsobear @ClarkXia @luhc228 cc

**Comment by imsobear** [comment]
@chenjun1011 remix 貌似还有个 params 我记得？

**Comment by chenjun1011** [comment]
> @chenjun1011 remix 貌似还有个 params 我记得？

已补充
