### ISSUE TITLE
404 500 路由

### ISSUE THREAD

**Issue by luhc228** [ice-lab/ice-next#133]
400
- 有 `pages/404.tsx`，则使用此自定义组件
- 没有 `pages/404.tsx`，默认使用 `.ice/404.tsx`

500 
TODO

**Comment by chenjun1011** [comment]
似乎不需要 500 的路由

现在的逻辑是如果 SSR 渲染出错，降级到 CSR（只渲染 Document），Document 的渲染逻辑相对简单，如果渲染出错在本地构建时就可以发现修复了。感觉没必要在 Document 外再加一层 catch，来渲染 500 了
