### ISSUE TITLE
页面无限刷新问题

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#139]
一旦加载的脚本发生错误，将触发刷新，而刷新无法解决错误的情况下将无限刷新
https://github.com/ice-lab/ice-next/blob/11fbac8589264427e829132cd4918eccaf770b0d/packages/runtime/src/routes.tsx#L29

**Comment by luhc228** [comment]
目前看没必要 reload，直接打印 error 出来即可。

这段逻辑可以去掉
