### ISSUE TITLE
App 上是否有必要存在 getData

### ISSUE THREAD

**Issue by chenjun1011** [ice-lab/ice-next#160]
App 上提供的 getData 功能，为获取 app 级别的数据提供了一个口子。

但同样的能力，似乎也可以通过全局的 layout + context 来实现。由 layout 定义 getData，获取 app 级别的数据，赋值给全局的 Provider。

```tsx
export default () => {
  const data = useData();

  console.log('render Layout', 'data', data);

  return (
    <AppDataProvider value={data}>
      <Outlet />
    </AppDataProvider>
  );
};

export function getData() {
  //...
}
```

这样能力等同，但框架所做的事情会简化不少。比如，在做数据预请求相关的处理时，只需要关注路由组件即可，不用增加很多 app 级别的特殊处理。

**Comment by imsobear** [comment]
- Document 里无法消费，类似我上次说的动态指定全局 title 的场景
- 还没来得及讨论的一块：appConfig 配置项有的需要依赖 initialData

**Comment by chenjun1011** [comment]
Document 里需要消费的话，用 layout 的 getConfig 也是可以满足的

**Comment by imsobear** [comment]
我说的第二个诉求，之前想过这种方式：

```js
export async function getData() {
}

export default((initialData) => {
  return {
  };
});
```

**Comment by chenjun1011** [comment]
getData -> getAppData

**Comment by chenjun1011** [comment]
route 的 getConfig 入参是 {data: routeData}
getAppConfig 的入参是  appData，要不要统一格式 ？
