### ISSUE TITLE
CSR 构建 HTML 时解耦对业务 Bundle 的依赖

### ISSUE THREAD

**Issue by chenjun1011** [ice-lab/ice-next#199]
类似 https://github.com/ice-lab/ice-next/pull/188 中的场景，如果页面 Bundle 加载失败，目前会导致 HTML 构建失败。

可以尝试将 getConfig 单独构建，来解耦

**Comment by chenjun1011** [comment]
解决上述问题，需要做到：能为不同产物按需提取页面内容（包含 dev 阶段）。

### 产物分析

目前，Route 组件包含的内容有：

- default （组件）
- getConfig
- getData

几种构建产物，各自需要的内容如下：

CSR 的页面 Bundle

- default
- getConfig

CSR 的 data-loader

- 只需要 getData （只 import 有 getData 的模块）

SSR 产物

- 用于 SSR/SSG 时，需要所有内容
- 用于 CSR 渲染 HTML 时，只需要 getConfig （只 import 有 getConfig 的模块）

### 社区实现

Remix 下的实现

- 通过 esbuild 按需为每个 route 组件构建一次，分析出组件的 exports
- 在构建 CSR 时，通过 esbuild 的 plugin 能力，按白名单过滤
- https://github.com/ice-lab/ice-next/issues/46
- https://github.com/remix-run/remix/blob/46b96f53e8477dd9404d55e75b320775c3a8a7a4/packages/remix-dev/compiler/plugins/browserRouteModulesPlugin.ts#L59

next.js

- 通过 swc 实现
- https://github.com/vercel/next.js/pull/27552/files#diff-47027a187709b42043eeb1756742c995a8d7543bad20f0c7b62dcd9df269df59

**Comment by ClarkXia** [comment]
1. 预分析页面导出：按分析结果动态生成对应模版
2. client bundle 移除 getData 代码（swc 定制）

**Comment by chenjun1011** [comment]
esbuild 下 treeShaking 的测试结果：

即使在 dev 阶段（非 minify）下也会进行 treeShaking，但如果依赖中存在立即执行的代码，则不会被移除。

示例代码如下:

第三方代码
```
// bar.js
console.log('bar');

export default function bar() {
  return 'bar';
}
```

路由组件
```jsx
import bar from '../components/bar';
import styles from './index.module.css';
import './base.css';

export default function Home(props) {
  bar();
  return (
    <>
      <h2 className={styles.title}>Home Page</h2>
    </>
  );
}

export function getConfig() {
  return {
    title: 'Home',
    meta: [
      {
        name: 'theme-color',
        content: '#000',
      },
      {
        name: 'title-color',
        content: '#f00',
      },
    ],
    auth: ['admin'],
  };
}
```

构建入口
```
import { getConfig } from '@/pages/';
export default getConfig;
```

构建产物如下：

```
// src/components/bar.tsx
console.log("bar");

// src/pages/index.tsx
function getConfig() {
  return {
    title: "Home",
    meta: [
      {
        name: "theme-color",
        content: "#000"
      },
      {
        name: "title-color",
        content: "#f00"
      }
    ],
    auth: ["admin"]
  };
}
```

如果希望把立即执行的代码也移除，需要在项目级的 package.json 配置 sideEffects （注意，会把 css 也剔除，需加白名单）

```
  "sideEffects": [
    "*.css"
  ]
```

参考
https://esbuild.github.io/api/#ignore-annotations
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
