### ISSUE TITLE
三方依赖是否要打包到 server bundle 里面？

### ISSUE THREAD

**Issue by luhc228** [ice-lab/ice-next#201]
## 背景

目前 ICE 3.0 server 端打包时，默认会把三方依赖 externals。而目前遇到两个场景，在开启 ssr 时，会报错：

### 场景1：三方依赖未合理导出 ESM 产物

部分的三方依赖写了 package.json 中写了 `main` 字段(一般是 cjs 的产物)和 `module` 字段(一般是 esm 的产物)，但是没有 `exports` 字段。而我们目前打包出来的server bundle 的格式是 ESM（即引入模块是 `import xxx from 'xxx';`）。框架在 nodejs 中加载 server bundle 时，由于只能读到 `main` 字段对于的 cjs 产物，导致无法正确拿到模块导出的对象。

![image](https://user-images.githubusercontent.com/44047106/167369984-91fab9e2-5228-4b4d-afb4-fc7d49398480.png)
![image](https://user-images.githubusercontent.com/44047106/167369999-145351af-f395-438b-8c56-9bb7b91a8a40.png)

### 场景2：三方依赖中加载了非 JS 模块
三方依赖中在 JS 里加载了非 JS 模块（比如 CSS），而由于我们在 nodejs 中加载 server bundle 时，是通过 `import('./build/server/index.mjs')` 的方式加载的，而 import 是不支持解析非 JS 模块的，因此会出现语法解析错误。

## 临时解决方案

把这部分有问题的三方依赖写在 compileDependencies 中

## 方案
1. 三方依赖可以考虑打包到 server bundle 里面，就能避免用户手动配置 compileDependencies 中。但只不过是 bundle 体积会增大

**Comment by maoxiaoke** [comment]
补充一个场景：当三方 web 没有设置 `type: module` 时，会导致加载 esm 模块错误。

```json
module: 'esm/index.js',
exports: {
  "import": "esm/index.js"
}
```
![31F8FAA3-C56E-4411-8825-D79CC8C1FCB9](https://user-images.githubusercontent.com/13417006/167536126-2fe94c89-01f8-416a-ab6b-6601d79d898c.png)

**Comment by ClarkXia** [comment]
通过预编译解决

**Comment by imsobear** [comment]
通过预编译解决：

- start：预编译 + esbuild(external all)
- build：没有预编译+ esbuild(external false)

**Comment by imsobear** [comment]
server.entry 里注入 process.env 的逻辑可以干掉了，因为所有代码都走了编译因此统一走 define 即可。

**Comment by luhc228** [comment]
如果预编译的结果是 esm 格式时，可能会遇到这个问题：https://github.com/evanw/esbuild/issues/1921

因此预编译的结果需要支持 cjs

**Comment by luhc228** [comment]
支持在 `ice.config.ts` 中配置预编译的格式和是否打包依赖

- (默认)bundle=false + format='esm'：预编译 预分析的依赖(dev 会重定向到 `node_modules/.ice/deps/xx`，prod 会打包进去)，输出 `server/index.mjs`
- bundle=true + format='cjs': 所有依赖打包进去，并输出 `server/index.cjs`
- bundle=false + format='cjs': 打包预分析的依赖（包括 `@ice/runtime`）但会 external `react `和 `react-dom`，并输出 `server/index.cjs`
