### ISSUE TITLE
css 资源加载顺序以及必要性

### ISSUE THREAD

**Issue by luhc228** [ice-lab/ice-next#206]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/44047106/167611168-055d3d46-4818-48f7-9cbf-5418f633c3ec.png">

- `/css/loader.css` 没必要加载进来，因为都在 main.css 和 路由级别的 css 中存在
- `main.css` 应该在前面，路由级别的 css 和 vendor css 在后面

**Comment by chenjun1011** [comment]
本质问题应该是 data-loader 构建时，tree shaking 没成功，把 route 的所有内容都构建进来了
