### ISSUE TITLE
data-loader 构建问题

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#217]
目前 data-loader 的构建作为一个 entry 入口执行编译，带来了如下的问题：
1. 在默认情况下会引入所有组件， 默认情况下会构建出全量组件内容，包括所有自执行逻辑、样式等 #206 #218
2. 由于在同一个页面引入多个 entry 的 chunk 从而导致了 hmr 失败问题
3. 多 entry 构建影响 chunk 输出，包括 `runtimeChunk` 配置问题（会导致 umd 规范导出存在问题）#92

**Comment by chenjun1011** [comment]
已解决 https://github.com/ice-lab/ice-next/pull/246
