### ISSUE TITLE
app.ts 入口职责和能力确定

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#221]
app.ts 入口目前包含两部分职责：应用配置和初始化数据获取

### 方案设计

目前的设计：
```js
export const getAppData = async () => {};
export const getAppConfig = (appData) => {};
```
`getAppData` 在项目启动前，阻塞渲染执行。通常为了提供用户权限相关信息，结合状态管理可能还会有初始化状态的需求。
`getAppConfig` 用于对应用运行时能力进行配置，目前包括以下能力：

```js
{
  app: {
    rootId: 'ice-container',
    mountNode: document.getElementById('ice-container'),  // 更灵活的 rootId
    parseSearchParams: true,  // 自动解析 query 参数，推荐使用 react-router 6 的逻辑实现
    strict: false,  // React.StrictMode
    addProvider: ({ children }) => <>{children}</>, // 全局 Provider，推荐通过全局 layout 承载
    errorBoundary: true, // 简化 errorBoundary 相关配置，自定义诉求推荐在全局 layout 中添加
    ... // onShow / onHide / onLaunch / onPageNotFound / onError / onUnhandledRejection / onTabItemClick 等应用生命周期
  },
  router: {
    type: 'hash',
    basename: '/ice',
    ... // 其他路由相关能力
  }
}
```

上述配置更加推荐直接以对象的方式返回，原因主要基于以下几点考虑：
- 应用核心提供的配置原则上不再支持三方插件扩展
- 在工程启动或者构建时大量依赖这份配置，比如 basename（国际化路由生成诉求）、rootId（document 渲染诉求）、errorBoundary（未使用代码移除诉求），如果依赖 appData 则需要额外的异步执行
- 绝大多数场景下配置不存在依赖 appData 动态化

即最终导出方式为：

 ```js
export const getAppData = async () => {};
export const appConfig = {};
```

### Auth  / store 等依赖初始化场景的处理

src/app.ts 上的导出内容除 appConfig 和 getAppData 为内置方法之外，支持其他的导出，并通过 runtime 插件机制由具体的插件进行消费，比如 Auth 场景可以通过以下方式进行设计：

```js
// src/app.ts
export const auth = async () => {
  return { initialAuth: ['admin'] };
};
```

> 在 ice 2.x 设计中，auth 字段被动态注册进 appConfig，并且初始化数据逻辑耦合了 appConfig.app.getInitialData

### getAppData 职责定位

对于通用的初始化场景，比如用户信息显示等可以直接依赖 getAppData 完成初始化逻辑：

```js
// src/app.ts
export const getAppData = async () => {
  return { username: 'clark', avatar: 'https://xxx.com/avatar.jpg', userID: '123' };
};
```
```js
// src/pages/layout.tsx
import { useAppData, Outlet } from 'ice';

export default () => {
  const { username,  avatar } = useAppData();
  return (
      <>
        <Nav>{username}<img src={avatar} / ></Nav>
        <Content>
          <Outlet />
        </Content>
      </>
    );
}
```

```js
// src/pages/index.tsx
import { useEffect } from 'react';
import { useAppData } from 'ice';

export default () => {
  const { userId } = useAppData();
  useEffect(() => {fetch('/api/info', { userId })}, []);
  return <></>;
}

```

一些历史讨论：
- https://github.com/ice-lab/ice-next/issues/160

**Comment by chenjun1011** [comment]
目前包含的主要职责
- getAppData 获取全局数据
- getAppConfig 获取全局 Config

getAppData
- 提供全局性的数据，供页面和运行时插件使用，对应 useAppData
- 替代方案：在全局 layout 里通过 Context 实现

getAppConfig
- meta/title
  - 全局 layout 可以实现同等能力
- addProvider
  - 全局 layout 可以实现同等能力
- strict
  - 全局 layout 可以实现同等能力
- auth 等供插件使用的数据
  - 由全局 layout 获取用户信息，以 Context 提供给页面消费
  - 页面级别，主动包裹 Auth 组件，进行权限控制
  - 相比原来 plugin 的实现方式：
    - 优势：所见及所得，框架逻辑简化
    - 缺点：每个页面需要主动包裹这类功能组件
- rootId
- router/basename

**Comment by ClarkXia** [comment]
结论：
- 移除 getAppConfig，有 全局 layout 承载
- 默认导出 appConfig

**Comment by imsobear** [comment]
改动的原因、改动后常见场景代码怎么写，建议补充下
