### ISSUE TITLE
CSS 打包策略

### ISSUE THREAD

**Issue by luhc228** [ice-lab/ice-next#226]
ICE 3.0 下默认是启用了分包。大部分情况下，访问一个页面时会加载3个 css 资源：
- main.css：公共的 css 样式，比如 `src/global.css`
- page.css：页面的 css 样式，比如 `pages/home/index.css`
- vendor.css：第三方依赖中的 css 样式，一般是组件库的 css 代码，比如 `vendor~antd-mobile.css`

一般来说，main.css 文件体积很小（1k 不到），如果同时请求资源的数量过多，可能会影响首次访问页面的性能。

可以讨论下是否可以有一个选项将 main.css 和 vendor.css 合并成一个 bundle？

**Comment by ClarkXia** [comment]
通过优化默认的分包策略来处理
