### ISSUE TITLE
升级 Vite 3.0

### ISSUE THREAD

**Issue by usercao** [ice-lab/ice-next#231]
`Vite 3.0`快发布了，`ICE 3.0`可否跟进更新？

**Comment by ClarkXia** [comment]
3.0 我们会考虑专注在 webpack 领域来提升开发体验

**Comment by usercao** [comment]
> 3.0 我们会考虑专注在 webpack 领域来提升开发体验

@ClarkXia @imsobear 上述具体是什么意思呢？

1. `ICE 3`会专注`Webpack`不再支持`Vite`

2. `ICE 3`延用`ICE 2`的`Vite 2`相关逻辑不再进行更新

3. `ICE 3`优先保证`Webpack`的开发体验并在较为完善的情况下升级到`Vite 3`（升级时间随缘）

#### 如果是1、2两种情况希望 ICE2 提供一个升级 React 18 的更新可以方便用户自由选择

**Comment by usercao** [comment]
看到了[icepkg](https://github.com/ice-lab/icepkg)仓库，冷启动/热重载/打包如果真比Vite快感觉也不错，希望到时出个时间对比图

**Comment by ClarkXia** [comment]
👌 后续我们会出一些 benchmark，包括构建时间和页面性能
