### ISSUE TITLE
测试覆盖率 ci 流程

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#264]
1. 优化测试覆盖率计算，目前测试覆盖率计算包含了 examples / bundles 目录，需要剔除
2. 测试覆盖率持续提升至 80+%（目前 50%+，含其他不因计算的文件）
3. 增加测试覆盖率自动回复，确保测试覆盖率不会因新增功能下降

**Comment by wssgcg1213** [comment]
- 确定一下规则, 例如哪些属于不能计算的文件
- PR 修改的文件需要一个覆盖率下限限制
