### ISSUE TITLE
测试环境下的 esm 执行表现不一致

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#27]
jest 环境下的 esm 执行和正常 node 环境通过 import 执行有所差异，包括通过 esbuild 构建的产物内容也有所不同，需要确保执行逻辑在两个环境下相同

**Comment by chenjun1011** [comment]
更新下，这个问题可能不是 jest 环境导致的，而跟 build 命中在什么目录下执行，或 link 的机制有关

现象：

场景1：在 examples/basic-project 目录下执行 build

- 不会构建 @ice/runtime 的相关内容

场景2：在 ice-next 根目录下，通过 jest 执行 build

- 产物包含 @ice/runtime 和 @ice/runtime 下的依赖, 例如 react-dom
- 由于 react-dom 不支持 esm，还会额外引入 require

之所以有上面的怀疑，是因为测了这样一个场景：

对 esbuild 配置 external node_modules 后，通过  plugin 的机制，打印了 onResolve 后的所有文件目录，二者剩下的文件文件是不一样的 （esbuild  external 逻辑会在 plugins 应用之前跑一遍）

```
    external: ['./node_modules/*'],
    plugins: [
      {
        name: 'external-plugin',
        setup(build) {
          build.onResolve({ filter: /.*/ }, (args) => {
            console.log(args.path);
          });
        },
      }
    ],
```

场景1 中打印的 path 不包含 @ice/runtime  下的其他文件，@ice/runtime 的 external 是生效的

场景2 中打印的 path 包含了 @ice/runtime 下的一些文件，@ice/runtime 的 external 没生效

```
@ice/runtime
./runtime.js
./runtime.js
react
react
react
./serverRender.js
./render.js
./AppErrorBoundary.js
react-dom
react-dom
./AppContext.js
```

场景2 external 没生效，所以将  @ice/runtime  及其依赖构建进去了，而 react 不支持 mjs，所以额外引入 require 的 polyfill

**Comment by chenjun1011** [comment]
另外一个有点类似的问题是：

`.ice/index.ts` 下引入的 `@ice/plugin-auth/runtime/Auth` 这个包

它的相关依赖，比如 react 都会被 esbuild 构建到 bundle 中，而没有正常 external 掉

```
import { useAppContext } from '@ice/runtime';
import { withAuth, useAuth } from '@ice/plugin-auth/runtime/Auth';

export { useAppContext, withAuth, useAuth };
```

没有正常 external react，会引起两个问题：

- 项目中存在多分 react
- 由于 react 不支持 esm，会引入额外的 require polyfill，导致 jest 的 esm 环境下无法正常执行代码

另外，补充两个信息：
- 是否 external react 跟 react 是否支持 esm 无关，测试了 react-route-dom，同样会被构建到 bundle 中
- @ice/plugin-auth/runtime/Auth 配置了 alias，被 alias 到 `../../packages/plugin-auth/runtime/Auth.tsx`

**Comment by luhc228** [comment]
![image](https://user-images.githubusercontent.com/44047106/160071211-e459be2e-c18b-423b-85f6-71169dd3e2a0.png)

**Comment by ClarkXia** [comment]
已通过统一的 external 逻辑处理
