### ISSUE TITLE
removeExportExprs 时，立即执行代码是否应该被移除

### ISSUE THREAD

**Issue by chenjun1011** [ice-lab/ice-next#275]
当下结论：不移除，假设移除 getData，保留 default，如果移除 getData 的时候同时移除立即执行代码，有可能导致 default 内的逻辑出错。

后续如果需要解决这类问题，可以考虑
- https://github.com/Andarist/babel-plugin-annotate-pure-calls
- 提供 filter export exprs 的能力，比如只导出 getData 及其相关依赖

**Comment by ClarkXia** [comment]
- 新增移除 Top level call 的 swc 插件
- 保留现有 removeExportExprs 能力
