### ISSUE TITLE
bundles 包大小优化

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#278]
- fork-ts-checker-webpack-plugin（external typescript）
- 移除 @swc/core 依赖（需要考虑 teser-webpack-plugin 压缩支持 swc 的场景）
- ...

**Comment by wssgcg1213** [comment]
目标: 
1. 减少安装时间
2. 减少安装体积 (比如 < 150M?)

本地可以用 ncdu (brew install ncdu) 查看 node_modules 路径  

cc @andycall

**Comment by wssgcg1213** [comment]
```
└─┬ @ice/app@3.0.0-alpha.36
  └─┬ trusted-cert@1.1.3
    └─┬ inquirer@7.3.3
      └── rxjs@6.6.7
```
联系 @yingchun.fyc 帮助处理

**Comment by luhc228** [comment]
> 

trusted-cert 中依赖的 inquirer 只是在 cli 命令行的时候用到，可以考虑预打包掉，减少体积
