### ISSUE TITLE
是否可以开一个roadmap？

### ISSUE THREAD

**Issue by usercao** [ice-lab/ice-next#291]
感觉发布日期遥遥无期😂

**Comment by wssgcg1213** [comment]
急得话可以先使用 alpha 版本, npm dist-tag = alpha

**Comment by usercao** [comment]
这也没文档啊😅我是外部用户不知道具体做了哪些改变

**Comment by ClarkXia** [comment]
> 这也没文档啊😅我是外部用户不知道具体做了哪些改变

630 会有一版内测，配套部分文档，后续我们会以周版本迭代的当时管理

**Comment by usercao** [comment]
太棒了👍
