### ISSUE TITLE
ICE 3 Document

### ISSUE THREAD

**Issue by luhc228** [ice-lab/ice-next#299]
第一期文档分工：
- [x] 关于 @wssgcg1213
- [x] 快速开始 @luhc228
- 基础
  - [x] 开发环境 @luhc228
  - [x] 目录结构 @luhc228
  - [x]  脚手架 @luhc228
  - [x]  应用入口 @ClarkXia
  - [x]  路由 @chenjun1011
  - [x]  样式 @luhc228
  - [x]  数据请求 @chenjun1011
  - [x]  静态资源 @ChrisCindy
  - [x]  构建部署 @luhc228
  - [x]  配置 @ClarkXia
  - [x]  环境变量 @wssgcg1213
- 进阶
  - [x]  定制 HTML @chenjun1011
  - [x]  SSG @chenjun1011
  - [x]  SSR @chenjun1011
  - [x]  Mock @luhc228
  - [ ]  一体化 @luhc228
- [x]  从 Rax 升级 @answershuto

**Comment by wssgcg1213** [comment]
- [ ] v3 站点部署 + ice.work 增加 v3 链接 @wssgcg1213
- [ ] 内部版本部署 @wssgcg1213

**Comment by wssgcg1213** [comment]
- [ ] 静态资源部分能力需要验证 @ClarkXia
- [ ] 数据模拟 Mock 需要增加 json exclude 规则 @luhc228 
- [ ] 插件开发: @ClarkXia 
- [ ] 构建部署 @luhc228 
- [ ] 新增 appear 文档 @wssgcg1213 
- [ ] rax 升级文档补充 @answershuto
