### ISSUE TITLE
ICE3 的 Rax 迁移文档 TODO

### ISSUE THREAD

**Issue by answershuto** [ice-lab/ice-next#340]
* 增加 React DSL 用户 Appear 事件使用方法
* ice/picture 文档

**Comment by usercao** [comment]
ICE3的文档考虑用[VitePress](https://cn.vitejs.dev/)吗？比ICE2的文档看起来美观清晰很多

**Comment by wssgcg1213** [comment]
@usercao 暂时没有计划切换, 使用的是 docusaurus, 目前够用了~ UI 都是可以定制的

**Comment by usercao** [comment]
> @usercao 暂时没有计划切换, 使用的是 docusaurus, 目前够用了~ UI 都是可以定制的

希望UI可以更加现代美观一点
