### ISSUE TITLE
ICE3配置式路由文档缺失

### ISSUE THREAD

**Issue by usercao** [ice-lab/ice-next#347]
[路由 | 飞冰 ICE](https://ice-v3-czrs32e26-ice-v3.vercel.app/docs/guide/basic/router) 现在是没有配置式路由了吗？

**Comment by luhc228** [comment]
目前仅支持约定式路由。

你对配置式路由有什么需求吗？

**Comment by usercao** [comment]
就是因为有配置式路由才用的ICE2啊，这升级直接给我干碎了😅

**Comment by usercao** [comment]
再则ICE2的用户如果使用的配置式路由写的项目，现在如何兼容升级？简直是重大破坏性更新了

**Comment by usercao** [comment]
ICE2官方文档着重标记推荐 [icejs 推荐使用 配置式路由 进行应用的路由管理](https://ice.work/docs/guide/basic/router#:~:text=icejs%20%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8%20%E9%85%8D%E7%BD%AE%E5%BC%8F%E8%B7%AF%E7%94%B1%20%E8%BF%9B%E8%A1%8C%E5%BA%94%E7%94%A8%E7%9A%84%E8%B7%AF%E7%94%B1%E7%AE%A1%E7%90%86)，ICE3升级完全脱离历史包袱了😅

**Comment by usercao** [comment]
看完了ICE 3 Beta的文档，感觉非常难受（例如页面数据请求部分`request`没了，推荐的`getData`也没有拦截器相关文档 / 定制 HTML部分变成了TSX的入口文件，[而且在`@iceworks/spec`规则中警告使用的`dangerouslySetInnerHTML`，现在却变成了官方推荐风格]），各种地方都充满了对ICE2的不兼容，如果说ICE2是可供用户任意组合创造的乐高积木，ICE3却变成了合金成品模型，感觉ICE3换个名字成立一个新项目也没有问题。

**Comment by ClarkXia** [comment]
> 看完了ICE 3 Beta的文档，感觉非常难受（例如页面数据请求部分`request`没了，推荐的`getData`也没有拦截器相关文档 / 定制 HTML部分变成了TSX的入口文件，[而且在`@iceworks/spec`规则中警告使用的`dangerouslySetInnerHTML`，现在却变成了官方推荐风格]），各种地方都充满了对ICE2的不兼容，如果说ICE2是可供用户任意组合创造的乐高积木，ICE3却变成了合金成品模型，感觉ICE3换个名字成立一个新项目也没有问题。

非常好的建议！ 关于你提到的几点建议，我简单说明下：
- 为什么不再推荐配置式路由，原因更多是基于约定式的路由我们可以去做很多优化，配置式灵活性过高导致一些方案和用户使用成本过高
- request 相关能力后续还是会提供，目前我们会更多结合 C 端场景去设计
- dangerouslySetInnerHTML 的确不太好，下个 beta 版本计划直接提供相关组件做内联

至于升级的问题后续会提供升级工具，待功能稳定后也会详细标注升级和 breakchange 的地方

**Comment by usercao** [comment]
```js
{
  path: 'name',
  exact: true,
  component: lazy(() => import('@/pages/name')),
  pageConfig: {
    title: 'name',
    scrollToTop: true,
    supportedChainIds: [networkConfig.xxx],
    auth: ['prod', 'test', 'dev', 'local', 'staging'],
    // each routing configuration may be different
    // more ...
  },
}
```

无法估算如上配置的几十个路由的项目改动需要多少工作量，没有直接用Vite搭建项目的主要问题是`index.html`不支持更改位置，ICE3直接把这个都干掉了，只能说哀莫大于心死。
