### ISSUE TITLE
修改 document.jsx 后 server bundle 没有重新编译

### ISSUE THREAD

**Issue by wssgcg1213** [ice-lab/ice-next#363]
在 PHA 插件中, DevServer 提供的 manifest.json URL，修改 document.jsx 后刷新对应 document 字段内容不会更新

**Comment by ClarkXia** [comment]
跟 PHA 插件逻辑无关，主要是 document 没有被源码引入，导致变更后没有出发重新编译

**Comment by ClarkXia** [comment]
目前修改后刷新页面即可返回最新 document
