### ISSUE TITLE
inlineStyle  能力补充

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#383]
目前已支持 inlineStyle 基础能力，但对于以下用法需要配合 ast 语法转化，尚未支持：

```js
import './index.css';
// test 类定义在 index.css 中
export default () => (<div className="test">test<div>);
```

**Comment by wssgcg1213** [comment]
Rax 对应能力 https://github.com/raxjs/rax-app/blob/master/packages/babel-plugin-transform-jsx-stylesheet/README.md

**Comment by wssgcg1213** [comment]
此类使用 css 文件支持, 不再考虑转换成 inline
