### ISSUE TITLE
状态管理方案

### ISSUE THREAD

**Issue by wssgcg1213** [ice-lab/ice-next#395]

**Comment by luhc228** [comment]
[WIP]
## 背景

回顾 ICE 1.x/2.x 以及 rax-app 3.x，两个框架状态管理方案都是在 icestore (react-redux) 基础上，支持自动包裹全局和页面级别的 `<Provider />`、按需开启状态管理等。但从 issue 和答疑的反馈来看，目前开发者在使用状态管理方案的时候还是有一定的上手成本：
- reducer 和 effects 区别
- Provider 没有包上，报错：`Cannot read properties of null (reading 'store')` （答疑较多，一般都是页面路由嵌套二级以上）
- 开发者写的 store.ts 的目录不对，导致状态管理没有开启
- 

另外，icestore 是基于 redux 和 react-redux，体积相对较大（约 xxxx kb），在无线端场景下可能导致 bundle 体积过大的问题

**Comment by luhc228** [comment]
TODO:
- 需要支持全局初始状态 initialStates

**Comment by luhc228** [comment]
#### 讨论：切换页面再次进入原页面后是否需要重新初始化页面状态？

用户对于重新初始化页面状态还是有诉求的：https://github.com/dvajs/dva/issues/907

ICE 2 的默认行为是会重新初始化页面状态，用户可以通过配置关闭此行为。[详见](https://ice.work/docs/guide/basic/store/#%E8%B7%AF%E7%94%B1%E5%88%87%E6%8D%A2%E5%90%8E%E9%87%8D%E6%96%B0%E5%88%9D%E5%A7%8B%E5%8C%96%E9%A1%B5%E9%9D%A2%E7%8A%B6%E6%80%81)

不过主流的状态管理方案一般没有自动重置状态的行为（仅维护一个全局状态），需要用户手动添加 reset 逻辑
- https://github.com/abhiaiyer91/redux-reset
- https://github.com/dvajs/dva/issues/907#issuecomment-694091897

**Comment by wssgcg1213** [comment]
> ### 讨论：切换页面再次进入原页面后是否需要重新初始化页面状态？
> 用户对于重新初始化页面状态还是有诉求的：[dvajs/dva#907](https://github.com/dvajs/dva/issues/907)
> 
> ICE 2 的默认行为是会重新初始化页面状态，用户可以通过配置关闭此行为。[详见](https://ice.work/docs/guide/basic/store/#%E8%B7%AF%E7%94%B1%E5%88%87%E6%8D%A2%E5%90%8E%E9%87%8D%E6%96%B0%E5%88%9D%E5%A7%8B%E5%8C%96%E9%A1%B5%E9%9D%A2%E7%8A%B6%E6%80%81)
> 
> 不过主流的状态管理方案一般没有自动重置状态的行为（仅维护一个全局状态），需要用户手动添加 reset 逻辑
> 
> * https://github.com/abhiaiyer91/redux-reset
> * [如何清空 redux 信息？ dvajs/dva#907 (comment)](https://github.com/dvajs/dva/issues/907#issuecomment-694091897)

SPA 中, 我们把多个页面组合成一个 Application, 这个数据是 App 的数据，所以不应该清空状态。  
如果业务需要在切换页面的时候重置状态, 这个属于业务逻辑范畴，提供 API 和生命周期回调让业务自己组合就可以了。
