### ISSUE TITLE
compatStyle 在 server 端执行环境下无法将 rpx 转 vw

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#402]
server 执行结果：

![image](https://user-images.githubusercontent.com/4219965/181486971-442ff5c2-08a6-4817-83a7-9ed40cb60d4e.png)

client 执行结果：

![image](https://user-images.githubusercontent.com/4219965/181487031-c5ac23d5-d1f7-40a8-b42b-21bdd320b463.png)

**Comment by answershuto** [comment]
https://github.com/ice-lab/ice-next/pull/409
