### ISSUE TITLE
UserConfig 中的 ssg 和 ssr 字段设计讨论

### ISSUE THREAD

**Issue by luhc228** [ice-lab/ice-next#407]
# 背景
目前 ssr 和 ssg 是通过以下两个字段分别开启/关闭的：

```ts
// ice.config.mts
import { defineConfig } from '@ice/app';

export default defineConfig({
  ssr: true; // 开启 ssr，默认是 false
  ssg: false; // 关闭 ssg，默认是 true
})
```

其中各个字段开启后的效果如下：
|                              | ssr = true  | ssg = true  |
| ---------------------------- | ---- | ---- |
| dev 阶段 HTML 包含页面内容   | Y    | Y    |
| build 阶段 HTML 包含页面内容 | N    | Y    |

## 对于 ICE 3 框架开发者：
- 目前框架内部逻辑有很多地方是同时依赖 ssg 和 ssr 两个字段进行判断的，比如 documentOnly, removeExportExprs 等
- renderMode 的值是根据 ssr 和 ssg 计算出来的，且 dev 和 build 阶段计算逻辑不一致和优先级，比较难理解
- 当独立开启 ssg 时，即 ssr 为 false 且 ssg 为 true ，dev 阶段表现是完全一致的，完全可以用一个字段代替
- 未来的设计，如果有更多的渲染方式，是无限扩展新字段吗

## 对于业务开发者：
- 开启 csr 的时候，为什么要同时把 ssr 和 ssg 设置为 false

# 方案

1. 参考 ice 2 的做法，只有 ssr 一个字段，有三个取值：
    - false: 关闭 ssr
    - true: 开启 ssr
    - 'static': 开启 ssg

**Comment by FuzzyFade** [comment]
还有种方案是，将 Rendering Pattern 对用户全部收敛为一个字段：
```ts
// ice.config.mts
import { defineConfig } from '@ice/app';

export default defineConfig({
  renderer: 'ssr' // 'csr' | 'ssr' | 'ssg' | 'island'  默认值 'csr'
})
```

**Comment by luhc228** [comment]
讨论结果：保持现状
