### ISSUE TITLE
框架品牌讨论

### ISSUE THREAD

**Issue by imsobear** [ice-lab/ice-next#442]
- 建议框架还是延续 icejs 的品牌，原因：
  - icejs 目前定位比较稳定，也有一些稳定的用户，再去改品牌对用户的体感不好
  - 飞冰/ICE 在社区的定位本身不太稳定，很多人认知都不太对，可以考虑慢慢舍弃掉
- 对外尽量不透出 ICE 3.0，icejs@3.0、icepkg 分开讲就可以，慢慢可以弱化 ICE/飞冰 的品牌概念，以 icejs、icepkg、icestark、components 这种单点的产品对外去讲就 OK，避免大家对于 ICE 代表什么越来越混乱，ice.work 彻底回归到 icejs 的官网
- 对内可以走 ICE 3.0 宣讲，代表完整的框架解决方案

**Comment by wssgcg1213** [comment]
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/3922719/184292022-3657b1ca-d025-44ee-9a63-ac45a589e33b.png">
刚随便画的, 框架名字叫啥感觉问题不大, 主要还是宣传需要 (易于认知和识别), 个人还是倾向于 `ICE 3`, 音节更少

**Comment by answershuto** [comment]
我不认为音节是命名的一个重要因素，举个例子：Vue 官网透出首页的信息是是 Vue.js ，实际上大家一般都会念 Vue，这个放在 icejs 与 ICE 3 上也是一样的，所以放在可传播性上，这个并不是影响命名的问题。名称是对产品的一个定义，以及考虑品牌的延续性或许更重要。

**Comment by imsobear** [comment]
- 现在社区对 ICE 可能有几种认知：桌面端应用、物料、低代码、框架、微前端……对了，可能还有 Design，这很烦也很难再纠正，所以放弃也是一个选择
- 我不同意框架用 ICE 3 的原因：1. icejs 已经做了两个版本了，口碑还可以，最好能继续延续 2. 如上所说，ICE 已经被赋予了太多概念，框架还要继续用 ICE 的话就得考虑怎么纠正过来（我觉得很难

**Comment by imsobear** [comment]
换回 ice.js 的话要改动的地方：NPM 包名 `@ice/app` -> `ice.js`，随之在 ice.config 里导入 defineConfig 的名字也要改下 https://github.com/ice-lab/ice-next/blob/master/examples/basic-project/ice.config.mts#L1

**Comment by radeon8** [comment]
npm还是 @ice/app 吧，我这项目里就不用改名了，
名称对外还叫 icejs

**Comment by imsobear** [comment]
> npm还是 @ice/app 吧，我这项目里就不用改名了， 名称对外还叫 icejs

你已经用起来了啊~~~

**Comment by answershuto** [comment]
强啊

**Comment by usercao** [comment]
能不能考虑下把配置式路由加上？这让ICEJS2用户如何方便升级呢？

**Comment by wssgcg1213** [comment]
Members 内部讨论了一下, 框架叫 ice.js, 加上 ICE PKG, ICESTARK, AppWorks 等等这些叫 ICE (飞冰), 对内讲 ICE 3 第三代终端框架体系 (包含核心框架和生态), 文档都是各个技术产品独立, 互链, 不过可能会引入一个 ICE 整体的 Portal 来把各个产品串起来和维护品牌

**Comment by wssgcg1213** [comment]
> 能不能考虑下把配置式路由加上？这让ICEJS2用户如何方便升级呢？

https://v3.ice.work/docs/guide/basic/config#routes  可以用这个方式在内部重定向路由, 相当于原先的`路由组件 - 路由路径`映射的方式
