### ISSUE TITLE
调试过程经常出现热更新资源404的情况，reload页面依旧 404，重启调试恢复正常

### ISSUE THREAD

**Issue by luhc228** [ice-lab/ice-next#450]
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/44047106/184838670-f0639ae3-4804-40df-ac43-a7408964b6a8.png">

**Comment by fattydevelop** [comment]
ICE3 "@ice/runtime": "1.0.0-rc.1", "@ice/app": "3.0.0-rc.1",

编译出错修复后大概率可以复现，还未找到必现路径

**Comment by wssgcg1213** [comment]
我感觉跟重复起 devServer 有关?

**Comment by ClarkXia** [comment]
目前排查出跟 splitChunks 逻辑相关

**Comment by wssgcg1213** [comment]
Same as [ #294 ](https://github.com/ice-lab/ice-next/issues/335)

**Comment by ClarkXia** [comment]
assets 信息走内存，理论上不会再出现资源 404 的情况
