### ISSUE TITLE
data-loader 问题讨论

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#459]
问题 1：data-loader 数据请求发起时间比预期要晚，目前看实在所有 js 请求结束后发起：
<img width="948" alt="image" src="https://user-images.githubusercontent.com/4219965/185281788-c1964495-0cb2-4d02-bb77-7657cfe06f37.png">

问题 2: data-loader 提取了请求部分逻辑前置执行，打包结果上会有重复逻辑，特别是对于 request 的配置初始化等，对于类似场景需要给出一定的解决方案

**Comment by chenjun1011** [comment]
对于问题1，应该是还存在些优化点，现在 page 的 chunk 输出在了 data-loader.js 前，实际应该挪到后面，调整后是这个加载顺序，应该符合预期？

![image](https://user-images.githubusercontent.com/1303018/185293152-c9cae4e5-baa5-4698-ab3c-cea7028e81cf.png)

**Comment by ClarkXia** [comment]
- data-loader 前置，对于使用 request 插件的情况，全局配置将会失效，并且 request 代码打包多份
