### ISSUE TITLE
Make SSR、SSG easier to use.

### ISSUE THREAD

**Issue by luhc228** [ice-lab/ice-next#460]
### 背景

之前讨论是 SSR 默认关闭的，SSG 默认开启。

不过即使 SSG 默认开启，对用户的要求就是不能写在 Node 端无法运行的 Code（比如 window, document），否则构建时会报错。

**Comment by wssgcg1213** [comment]
讨论结果：仍旧保持现状，即 SSR 默认关闭，SSG 默认开启。

需要做的三件事情
1. 提供文档指引，告诉开发者如何写出同构的代码
2. 提供变量和类似 https://docusaurus.io/docs/docusaurus-core#browseronly 的组件, 从 `ice` 中导出
3. 提供构建能力，能够在 SSR/SSG 环境下注入一些变量，例如
    ```js
       const location = createLocation('xxxx'); // ... 
       export default {
          location,
          window,
          navigator,
       };
    ```
> Tips: 实现中不能污染全局变量, 提供一个简易的 `new Function()` 环境执行即可
