### ISSUE TITLE
3.0 框架品牌方案讨论

### ISSUE THREAD

**Issue by imsobear** [ice-lab/ice-next#48]
## 方案 1 （3.0 现状）

- 品牌只透 ice 不透 icejs
- NPM 包名是 @ice/cli，对应的命令是 ice start/build

优缺点：

- 缺点：跟之前的 icejs 延续性不太好

## 方案 2（icejs 2.0 版本）

- 框架品牌是 icejs
- 包名 ice.js，对应的命令 icejs

优缺点：

- 缺点：`import {} from 'ice';` 有点对应不上

**Comment by ClarkXia** [comment]
主包名暂定：@ice/app

**Comment by imsobear** [comment]
用户对 icejs 的感知并不多，因此还是以 ICE 来推（方案 1），包名从原先的 `@ice/cli` 改为 `@ice/app`，同时 `@ice/pkg-cli` 也改为 `@ice/pkg`，保持对齐。
