### ISSUE TITLE
swc 插件提供只保留 getData 的能力

### ISSUE THREAD

**Issue by chenjun1011** [ice-lab/ice-next#487]
当构建 getData 时，只保留 getData 及其相关依赖（移除立即执行代码）
当构建 getConfig 时，只保留 getConfig 及其相关依赖（移除立即执行代码）
当构建 default 组件时，保留 defalut 方法及其相关依赖（不移除立即执行代码）

**Comment by ClarkXia** [comment]
相关 issue #447
