### ISSUE TITLE
getAppData 是否需要数据预请求

### ISSUE THREAD

**Issue by chenjun1011** [ice-lab/ice-next#513]
当只存在 getAppData  的时候（页面无 getData），getAppData 用于 Server 端获取 Document 所需数据，此时不需要构建 data-loader

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/1303018/189027816-4da966b5-e1e0-491e-8485-df2076ff5501.png">

**Comment by ClarkXia** [comment]
getAppData 应该也承担业务初始化数据的能力吧？

**Comment by luhc228** [comment]
还是有同样的问题 @chenjun1011

**Comment by luhc228** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/44047106/193204174-2e1daf5a-166d-4c33-9311-abd14756c624.png">
`loaders` 变量的初始化应该放在 data-loader 顶层先声明？
