### ISSUE TITLE
bundle.modern.js 基线讨论

### ISSUE THREAD

**Issue by imsobear** [ice-lab/ice-next#54]
## 背景

目前 `@ice/pkg-cli` 中 esnext 现在设定的版本是 es2022，这个基线要讨论下（2022 太高了），目标是收益最大化，两个纬度：

1. 尽量覆盖多的浏览器
2. 与 legacy 版本相比 bundle 大小能有尽量多的优化

![image](https://user-images.githubusercontent.com/2505411/160584718-6ca98802-1acd-4efd-8b65-a16a9e6b81a4.png)

## 讨论

- 基线选择
- 命名：esnext or modern or xxx

**Comment by imsobear** [comment]
基线选择：

> 刚才看项目的构建结果 一般 aysnc await 的体积占比较多 还会引入 regenerator-runtime

因此提名 ES2017，同时社区方案 microbundle 也是用的 ES2017

**Comment by imsobear** [comment]
命名：提名 modern

**Comment by maoxiaoke** [comment]
## browserList 配置

以 esm & [es2017](https://caniuse.com/async-functions,object-values,object-entries,mdn-javascript_builtins_object_getownpropertydescriptors,pad-start-end,mdn-javascript_grammar_trailing_commas_trailing_commas_in_functions) 的浏览器支持度：

1. es2017 浏览器支持度

![image](https://user-images.githubusercontent.com/13417006/160861978-43795d01-545f-4f47-b303-8a03ec9148cb.png)

2. esm 的浏览器支持度 

![image](https://user-images.githubusercontent.com/13417006/160862118-ac28f7e4-3af1-4234-9e8b-821313786ec5.png)

得到的 browserList 配置如下：

+ Chrome 61+
+ Safari 10.1+
+ firefox 60+
+ edge 16+
+ ios 11+

**Comment by ClarkXia** [comment]
- 补充 package.json 中 exports 配置

**Comment by imsobear** [comment]
- 基线选择 ES2017
- 概念上使用 modern 而非 esnext
  - Package 层面 
    - pkg 打包产物目录 `modern/`
    - dist 产物 `index.modern.js`
    - exports 中追加 modern 字段
  - App 层面
    - 最终构建出的产物为 index.modern.js
