### ISSUE TITLE
[RFC]无 html 的渲染引擎根节点

### ISSUE THREAD

**Issue by answershuto** [ice-lab/ice-next#554]
weex 等渲染引擎入口是 js 不是 html，需要改成使用 document.body 来作为渲染根节点，否则需要手动通过 JS 生成一个节点插入到文档中才可以正常 wrok 起来。考虑这样的场景如何透出修改节点的能力。

**Comment by wssgcg1213** [comment]
在 appConfig 里面支持修改?

**Comment by answershuto** [comment]
https://github.com/ice-lab/ice-next/pull/592
