### ISSUE TITLE
是否需要全局暴露 request context ？

### ISSUE THREAD

**Issue by chenjun1011** [ice-lab/ice-next#565]
目前的用法

在 getAppData 里中转 ctx，

```ts 
export const getAppData: GetAppData = async (ctx) => {
  return ctx;
};
```

然后通过 Document 消费

```tsx
export default function Document({ pagePath }) {
  const appData = useAppData<AppData>();
  if (appData?.documentData?.ssr) {
  }
}
```

搭建场景下，ctx 对应搭建透传的全局数据

问题：是否需直接暴露 ctx 给 Document 消费？例如提供 useRequestContext 的方法

**Comment by chenjun1011** [comment]
在 renderToHtml 方法中，增加参数，运行用户自定义传入数据
通过 useAppContext，消费自定义的数据

**Comment by ClarkXia** [comment]
- 暴露 useAppContext，支持 server 端扩展自定义的 app context
- 需要明确官方提供 useAppContext 都有什么信息
