### ISSUE TITLE
SSR 阶段 useAuth 返回 null 

### ISSUE THREAD

**Issue by luhc228** [ice-lab/ice-next#572]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/44047106/193239371-a0d9f2da-623c-4517-ba97-a5ee4f7f3c33.png">

**Comment by luhc228** [comment]
https://github.com/ice-lab/ice-next/pull/537  这个pr 合并以后即可解决

**Comment by ClarkXia** [comment]
原因是什么
