### ISSUE TITLE
getData 中使用 request 问题

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#600]
如果项目中使用 @ice/plugin-request 并且在 getData 中使用：

```js
import { request } from 'ice';

export async function getData() {
  return await request('/xxx');
}
```

全局配置的 request 参数将会失效，这样的差异对开发者的开发心智影响较大

**Comment by ClarkXia** [comment]
提供一种思路：
目前 data-loader 也会依赖到 getAppData（src/app.ts），导致 src/app.ts 多次被引入执行。
如果工程前置可以判断data-loader 的生成，在 client entry 的模版中可以不再引入 src/app，由 data-loader 中消费 src/app 并传递给主 bundle 项目的配置信息

**Comment by chenjun1011** [comment]
> 如果全量打包 app.ts，可能会导致 react 的重复打包

**Comment by chenjun1011** [comment]
> 提供一种思路： 目前 data-loader 也会依赖到 getAppData（src/app.ts），导致 src/app.ts 多次被引入执行。 如果工程前置可以判断data-loader 的生成，在 client entry 的模版中可以不再引入 src/app（在 data-loader 中可以顺便把 static runtime 初始化的事情也做掉），由 data-loader 中消费 src/app 并传递给主 bundle 项目的配置信息

如果全量打包 app.ts，可能会导致 react 的重复打包
