### ISSUE TITLE
hash router 问题

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#631]
开启 hash router 后，SSR 和 SSG 能力需要关闭，需要给出相应提示 / 框架层面默认处理

**Comment by luhc228** [comment]
1. 开启 hash 路由时，是否需要用户显式声明 ssg: false 和 ssr: false ？
3. 没有 src/pages/layout.tsx 的时候，matchRoutes() 返回的结果是空数组的，导致返回的是 Not Found 的页面
4. ssg 设置为 false 的时候，dev 返回的 html 结果和 build 生成的 html 结果不一致
5. ssg 设置为 false 后，html 的内容应该是什么？

**Comment by ClarkXia** [comment]
第二点：如果开启 hash，server 端不应该执行 matchRoutes 相关逻辑
第三点和第四点：html 应该就是纯document 内容，并且不同路由下的 html 内容一致
