### ISSUE TITLE
某些场景下需要移除 server 构建产物

### ISSUE THREAD

**Issue by luhc228** [ice-lab/ice-next#633]
server 构建产物比如在 assets 应用下是没有任何作用的，可以看下如果是在开启 ssr 才生成 server 目录，否则应该移除掉

**Comment by ClarkXia** [comment]
纯 csr 场景下考虑讲 server 目录作为中间产物，最终移除

**Comment by luhc228** [comment]
应该是关闭 ssr 的时候，统一把 server 的产物去掉。（ssg 不需要）
