### ISSUE TITLE
dropLogLevel : undefined 导致 console 在预发无法打印

### ISSUE THREAD

**Issue by answershuto** [ice-lab/ice-next#642]
RT

**Comment by wssgcg1213** [comment]
没明白描述的问题, 是指 dropLogLevel 被设置为 undefined 么

**Comment by answershuto** [comment]
设置  undefined 在预发没有打印，问题是没打印不是被设置。

**Comment by Tianyi-Mr** [comment]
1: 默认是都打出来的，但是发布预发后没有打印。
2: dropLogLevel 设置null ，ts提示没有这个选项 
![image](https://user-images.githubusercontent.com/44563214/199390729-bd56111a-0e9d-426b-a0e8-16311c954ef7.png)
结论就是不管怎么设置发布后就是不打印

**Comment by Tianyi-Mr** [comment]
> 没明白描述的问题, 是指 dropLogLevel 被设置为 undefined 么

1: 默认是都打出来的，但是发布预发后没有打印。
2: dropLogLevel 设置null ，ts提示没有这个选项
image
结论就是不管怎么设置发布后就是不打印

**Comment by Tianyi-Mr** [comment]
> 没明白描述的问题, 是指 dropLogLevel 被设置为 undefined 么
1: 默认不是设置应该所有的都能答应，但是结果是发布预发后无任何打印。
2: dropLogLevel 不能设置null, 但是强制设置 null或者undefined  在预发都不会打印。
![image](https://user-images.githubusercontent.com/44563214/199391204-23cdcc2c-b32f-4d51-b206-10a12251e125.png)
结论不设置默认不打印，设置也还是不打印。

**Comment by ClarkXia** [comment]
dropLogLevel 仅支持设置 string，undefined 的类型提示是不要设置 dropLevel

**Comment by Tianyi-Mr** [comment]
> dropLogLevel 仅支持设置 string，undefined 的类型提示是不要设置 dropLevel
dropLogLevel 删除这个key 不设置，理应debug log info 等都应该打印出来，但是发布预发后无任何打印

**Comment by ClarkXia** [comment]
提供下复现 demo 目前没发复现出来

**Comment by Tianyi-Mr** [comment]
> 提供下复现 demo 目前没发复现出来

我刚删除了下这个，可以了，应该是因为我升级了@ice/app 与@ice/runtime版本
