### ISSUE TITLE
[文档]路由篇需要给非约定式路由的配置提供指引

### ISSUE THREAD

**Issue by wssgcg1213** [ice-lab/ice-next#650]
TO - guide/basic/config/#routes

这个可以放在最底下, 原则上还是推荐使用约定式

**Comment by ClarkXia** [comment]
Mark：就近维护非路由组件，或者说是针对复杂场景约定式路由的目录实践

**Comment by lbarakidouji** [comment]
推荐从 配置式（ice.js 2.x） 变成了 约定式 是为何？
希望可以从文档中体现一下

**Comment by wssgcg1213** [comment]
> 推荐从 配置式（ice.js 2.x） 变成了 约定式 是为何？ 希望可以从文档中体现一下

好的, 正式发布的时候会有文章介绍的
