### ISSUE TITLE
useAppConext 上的 pageData 与 usePageContext 上的 pageData 重复

### ISSUE THREAD

**Issue by imsobear** [ice-lab/ice-next#66]
## 问题

- appContext 上既有 pageData 又有 initialData，不太好区分
- appContext 和 pageContext 上都由 pageData，职责重复

## 方案

- appContext 只有 initialPageData
- pageContext 只有 pageData，需要看下 PageWrapper 里包裹 PageContextProvider 时怎么拿到 pageData
- DocumentContext 可以尽量跟 AppContext 命名对齐下

**Comment by chenjun1011** [comment]
DocumentContext 也需要消费 pageData，如果 pageData 只在 PageContext 下拿到，有点绕了

**Comment by imsobear** [comment]
一个关联问题：appInitialData 的更新诉求 https://github.com/alibaba/ice/issues/5265#issuecomment-1089870430

**Comment by ClarkXia** [comment]
关联 issue https://github.com/ice-lab/ice-next/issues/84

**Comment by ClarkXia** [comment]
初步结论如下：
1. 提供 useInitialData API，初始数据不可变化
2. 变更诉求通过 Provider 和 useInitialData 定制新的 API，如果 useAuth / setAuth
