### ISSUE TITLE
AppData 类型没有导出

### ISSUE THREAD

**Issue by luhc228** [ice-lab/ice-next#665]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/44047106/200224438-6d4b2c65-78e1-4217-990d-9860d9240609.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/44047106/200224495-561b7ea1-3382-4722-95ea-6db8a18fbb1d.png">

**Comment by wssgcg1213** [comment]
需要文档修改 去掉这个 AppData

**Comment by wssgcg1213** [comment]
用户自己来定义 
```
interface AppData {}
```
