### ISSUE TITLE
ssr:false关闭好像不起作用啊

### ISSUE THREAD

**Issue by jianmaikj** [ice-lab/ice-next#673]
## What is the current behavior? 发生了什么？
defineConfig设置ssr:false关闭好像不起作用啊

还是会通过nodejs运行，报错：navigator is not defined
## Any additional comments? 相关环境信息？

- **ice.js Version**：1.0.0-rc.8
- **build.json Configuration**：
- **Node Version**:1.16
- **Platform**:win10

**Comment by chenjun1011** [comment]
再加上 ssg: false, 默认还是会用 SSG 去渲染页面

**Comment by wssgcg1213** [comment]
通过 nodejs 运行是一种行为，SSR 和 SSG 都会触发这个行为, 两种解决办法
1. 通过判断在浏览器中的状态后再访问 BOM Objects
2. 同时关闭 SSG 和 SSR
