### ISSUE TITLE
Context 支持调用插件 API

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#70]
## 背景

ICE 框架主包中定义框架所需的基础能力，而对于工程任务、工程配置的注册，目前必须通过 Context 提供的插件机制才可以添加，期望能够直接通过相关的 API，让主包里定义的能力更加清晰

## 方案

方案一：

对于注册相关的 API 支持直接调用，包括 registerTask、registerUserConfig、registerCliOptions

```js
const context = new Context({ ... });
context.regsiterTask('web', {});
```

方案二：

Context 支持在初始化时传入默认的任务和配置

```js
cont context = new Context({
  ...,
  tasks: [['web', {}]],
  config: {
    userConfig: {},
    cliOptions: {},
  }
})
```

**Comment by maoxiaoke** [comment]
想到一个问题：是否还需要对插件透出 registerTask ?

**Comment by ClarkXia** [comment]
结合多任务的场景重现设计下

**Comment by luhc228** [comment]
期望不需要 registerCliOptions 方法。目前 ICE3.0 注册 CLI 参数，都是通过 commander 注册的，build-scripts 不需要做校验
