### ISSUE TITLE
build 阶段全量编译 node_modules

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#71]
## 背景

框架对于三方依赖，默认采取的策略是不进行编译，主要基于以下几点原因的考虑：
- 大部分三方依赖的产物为 es5 产物，无须编译即可以正常执行
- 开发阶段，如果编译 node_modules 会带来较大的体验问题，编译速度大幅减低

但在 ICE 3.0 框架下，存在必须编译 node_modules 的场景：
- 多端代码移除
- 组件开发新的标准下，三方依赖编译 target 为 es6 甚至更高（有利于项目统一决定编译 target）
- 社区包比如 D3 发布的产物是 ES2017 的语法

因此框架需要兼顾开发体验和编译 node_modules 的诉求。

### 方案一：支持三方依赖预编译

预编译流程：
1. 项目开发启动前借助 esbuild 快速分析所有运行时三方依赖，分析结果缓存，再次启动时将进行对比，一旦分析结果和缓存不一致，将进行增量编译
2. 根据项目 browserlist 配置，将所有需要进行编译的三方依赖通过 esbuild 快速构建到临时目录
3. 项目启动后三方依赖将默认重定向到预编译产物

上述方案仅在 dev 过程中应用，build 阶段依旧需要全量编译，主要基于以下几点考虑：
- 多端场景下，三方依赖要么按端编译出多份产物，要么 build 阶段重新编译 node_modules
- 三方依赖预编译产物已完成一次编译和分包（基于 esbuild），对于 webpack 重新打包编译会有一定影响和差异（分包、treeshaking 等）

### 方案二：build 阶段全量编译

dev 阶段不进行 node_modules 编译，build 阶段全量编译 node_modules，如果dev 阶段调试兼容性需求下，增加开关主动开启全量编译
对于用户而言，无需透出 build 是全量编译，在 swc 编译的场景下编译速度降低不会太多

|  不编译 node_modules  |  不编译 node_modules  | 编译 node_modules  |
|  ----  | ----  | ----  |
| 编译文件数量 | 25 | 1275 |
| 编译耗时  | 8 - 9s | 12 - 14s |

> 增加 bizcharts 和 antd（默认移除 sideEffects）作为测试数据

对于一些已知模块可以默认不进行编译，比如：
- corejs
- @babel/runtime
- dev 依赖相关：react-refresh / @pmmmwh/react-refresh-webpack-plugin（overlay）/ webpack-dev-server（client）等
- 必要运行时：react / react-dom / react-router 等

未来更多场景都是现代浏览器的开发，方案二流程上更加简单，体验更好

**Comment by imsobear** [comment]
场景补充：社区包比如 D3 发布的产物是 ES2017 的语法

**Comment by imsobear** [comment]
方案二需要核心关注下数据，根据数据再看策略要不要调整，比如自动的黑白名单机制。

**Comment by ClarkXia** [comment]
> 方案二需要核心关注下数据，根据数据再看策略要不要调整，比如自动的黑白名单机制。

已补充一部分数据
