### ISSUE TITLE
Document 的更新逻辑

### ISSUE THREAD

**Issue by chenjun1011** [ice-lab/ice-next#73]
## 背景

当前，Document 的实现逻辑分为两块：

-  SSR 时，直接渲染 Document.jsx 组件
-  CSR 路由跳转时，通过 JS  更新页面特有的 Meta、links、scripts 等信息，具体实现如下：

https://github.com/ice-lab/ice-next/pull/51/files#diff-3141c0c9b82b2e4a3ce29247bd9c27b98be04bcba17e8da2cc15979c963a707f

存在的问题是需要维护两套逻辑

## 讨论

是否在 CSR 时，也直接渲染 Document 组件，大致实现思路如下

```
import { hydrate } from "react-dom";

hydrate(<Document><App /></Document>, document);
```

优势：

- 两端逻辑统一

缺点：

- 搭建类的场景，如果只渲染 Document，并且在 Document 中透出了一些自定义的数据， CSR 时无法对齐这些数据（一种可能的解决方案是，约定所有依赖服务端的数据，必须在 appData 或 pageData 中返回）

**Comment by ClarkXia** [comment]
两种方式表现上会有差异吗？

**Comment by imsobear** [comment]
这个主要看实现复杂度了，能这样实现的话当然是最好的。

**Comment by chenjun1011** [comment]
> 两种方式表现上会有差异吗？

如果两端节点对上，就不会重新渲染，视觉上没有差异的

**Comment by chenjun1011** [comment]
> 这个主要看实现复杂度了，能这样实现的话当然是最好的。

可以实现，本地跑了一个 Demo 了，迟点整理下代码发出来看看

**Comment by chenjun1011** [comment]
> 这个主要看实现复杂度了，能这样实现的话当然是最好的。

大致的改动如下，可以先看看 https://github.com/ice-lab/ice-next/pull/74/files （先忽略代码质量~）
