### ISSUE TITLE
日志输出方案

### ISSUE THREAD

**Issue by imsobear** [ice-lab/ice-next#79]
## 目标

- 输出日志格式一致
- 提升框架在构建&运行时的可调试性，同时辅助答疑场景

### 日志等级

- info: 默认输出
- warn: 默认输出
- error: 默认输出，使用 error 代表要退出进程的级别
- debug: 手动开启，输出简略调试日志（比如仅包含 err.message）
- trace: 手动开启，输出更为详细的调试日志（比如包含 err.stack）

### 日志输出规范

- 只能使用上述等级且按照场景使用
- 更具体的规范前缀等：待定

### 实现思路

通过命令行参数开启：

```bash
$ ice start --log-level=debug
$ ice build --log-level=trace
```

框架会做两件事：

1. 将 `--log-level` 转换成环境变量 [CONSOLA_LEVEL](https://github.com/unjs/consola/blob/master/src/types.js)
2. 将 `--log-level` 注入到运行时：`process.env.ICE_RUNTIME_LOG_LEVEL`

#### 构建时方案

直接使用 consola 即可，几点说明：

- consola 默认就是全局单例的模式，因此每个包自己依赖 consola 就可以，不需要顶层 new 一个实例然后到处传递
- 依赖包里使用 consola 的所有地方都会打印出对应日志，并不限于 ice 相关包

安装依赖：

```bash
$ pnpm add consola
```

代码中使用：

```js
import consola from 'consola';

consola.debug();
consola.verbose();
consola.error();
consola.info();
consola.warn();
```

#### 运行时方案

需要封装一个 log：

> 可以封装一个单独的 `@ice/log` 也可以直接放到 `@ice/runtime` 里，可以讨论下

```js
const log = {
  // 理论上不怎么会用到 info
  info: (...args) => {
     console.log(...args);
  },
  trace: (...args) => {
     if (process.env.ICE_RUNTIME_LOG_LEVEL === 'trace') {
       console.trace(...args)
     }
  }
};

export default log;
```

> log 的实现以及代码里调用的 log.xxx 是否要在构建时移除，需要讨论下

使用：

```js
// runtime 中
import log from './utils/log';
// 其他插件的 runtime
import { log } from '@ice/runtime';

log.debug('哈哈');
```

**Comment by ClarkXia** [comment]
consola 主要缺少 namespace 的能力，日志量变大之后可能会比较难以定位需要的日志

**Comment by ClarkXia** [comment]
运行时日志
- 项目开发者推荐直接使用 console 对于一些压缩移除以及使用认知上更简单
- 框架开发者，比如 @ice/runtime 中，输出日志的位置尽量用 process.env.NODE_ENV === 'development' 控制，已减少详细日志对于包大小影响，生产构建设计类似 React 的 errorcode 定位

**Comment by maoxiaoke** [comment]
1. 是否需要输出这么日志等级，参考 https://javapapers.com/log4j/log4j-levels/

+ Debug：主要为 application developer 提供的信息
+ Info
+ Warn
+ Error: 程序运行错误，但不会退出
+ Fatal：造成程序退出的错误

2. 建议为 Debug 增加 performace 信息，比如细节的执行时间

**Comment by ClarkXia** [comment]
结论：
框架内置工程推荐：consola
框架运行时仅输出错误日志，如果错误日志量大，参考社区 process.env.NODE_ENV === 'development' 的实现
