### ISSUE TITLE
SSR/SSG 开关

### ISSUE THREAD

**Issue by chenjun1011** [ice-lab/ice-next#83]
在 userConfig 中可以通过 ssr 和 ssg 分别进行以下控制：

- ssr
   - true（默认值）表示需要以 SSR 的方式进行投放（当下对产物没有影响，未来可能需要配合 FaaS 做一些调整）
   - false 表示不以 SSR 方式投放
- ssg
  -  true （默认值）构建时渲染完整的 HTML，Dev 阶段以 SSR 方式渲染
  -  false 构建时只渲染 Document

两个的开关的组合场景

- ssr:true ssg:true
  - Dev 阶段以 SSR 渲染
  - Build 构建产出完整 HTML
  - Server 端产物会以 FaaS 形式部署
- ssr:true ssg: false
  - Dev 阶段以 SSR 渲染
  - Build 只构建 Document
- ssr:false ssg: true
  - Dev 阶段以 SSR 渲染
  - Build 构建产出完整 HTML
- ssr:false ssg: false
  - Dev 阶段以 CSR 渲染
  - Build 只构建 Document

**Comment by ClarkXia** [comment]
`ssr:false ssg: true` 和 `ssr:true ssg:true` 的场景描述上是一致的，差异点应该是一体化场景下的表现会不一致
