### ISSUE TITLE
项目不依赖 browserlist 就会报错

### ISSUE THREAD

**Issue by imsobear** [ice-lab/ice-next#87]

**Comment by imsobear** [comment]
> 这个是 pnpm 模式下的问题，实际发布后在项目中使用正常

所以 examples 必须加这个依赖？项目里不需要？

**Comment by ClarkXia** [comment]
> > 这个是 pnpm 模式下的问题，实际发布后在项目中使用正常
> 
> 所以 examples 必须加这个依赖？项目里不需要？

是的
