### ISSUE TITLE
npm 包中 import 语句不加 .js 后缀编译不报错

### ISSUE THREAD

**Issue by imsobear** [ice-lab/ice-next#89]
比如 `@ice/runtime`：

```js
// 错误写法
import xxx from './utils/react-router-dom';
// 正确写法
import xxx from './utils/react-router-dom.js';
```

使用了错误写法后 watch 不会报错，但在项目里构建时就会报错，期望是组件编译时报错。

**Comment by luhc228** [comment]
需要在 tsconfig.json 中开启 compilerOptions.moduleResolution = 'node12'，并且保证 typescript 的版本是 next (估计是未来发的 4.7.x 的版本)
<img width="1577" alt="image" src="https://user-images.githubusercontent.com/44047106/162434171-cc607581-69f8-40d0-9e43-4e15d4aa4eb1.png">

**Comment by ClarkXia** [comment]
按标准写法增加 .js 后缀，由包编译工具决定是否需要自动补全
