### ISSUE TITLE
工程能力同 ice 2.x 对比

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#94]
|  ice 2.x  | ice 3.0  | 备注  |
|  ----  | ----  | ----  |
| --port  | ✅ | - |
| --host  | ✅ | - |
| --config  | ✅ | - |
| --disable-open  | ✅ | - |
| plugins  | ✅ | 调整推荐插件配置方式（推荐函数以获得类型提示） |
| alias  | ✅ | - |
| publicPath  | ✅ | - |
| devPublicPath  | ✅ | - |
| sourceMap  | ✅ | - |
| externals  | ✅ | - |
| hash  | ✅ | - |
| outputDir | ✅ | - |
| proxy | ✅ | - |
| define | ✅ | - |
| ssr | ✅ | - |
| --disable-mock  | 🚧 | - |
| --https  | 🚧 | 可选方案：自签证书 / devServer 自带 https 能力 |
| --analyzer  | 🚧 | - |
| --force  | 🚧 | 仅用于开发阶段 |
| dropLogLevel  | 🚧 | - |
| minify | 🚧 | 简化配置（true/false） |
| compileDependencies | 🚧 | 配合现有的 compileIncludes 能力 |
| eslint | 🚧 | - |
| tsChecker | 🚧 | - |
| ~fastRefresh~ | 🚧 | - |
| remoteRuntime | 🚧 | - |
| --disable-assets  | ❌ | 不常用通过环境变量控制日志输出详细程度 |
| --disable-reload  | ❌ | 配置禁止 fastRefresh |
| polyfill  | ❌ | 统一走 browserlist 文件 |
| terser | ❌ | 内置方案 |
| outputAssetsPath | ❌ | 梳理最佳目录实践 |
| devServer | ❌ | 不支持全量配置 devServer，按需开启 server 相关能力 |
| browserslist | ❌ | 统一走 browserlist 文件 |
| vendor | ❌ | 内置的分包实践 |
| libraryTarget / library / libraryExport | ❌ | - |
| cssLoaderOptions / lessLoaderOptions / sassLoaderOptions  | ❌ | 不支持 webpack loader 相关，内置配置 |
| postcssOptions / postcssrc | ❌ | - |
| ignoreHtmlTemplate | ❌ | - |
| entry | ❌ | 自定义场景走 client.entry.tsx |
| vite / vitePlugins | ❌ | - |
| swc | ❌ | - |
| store / auth / request / pwa / router | ❌ | - |
| disableRuntime | ❌ | - |
| babelPlugins / babelPresets / webpackPlugins / webpackLoaders | ❌ | 不推荐直接配置 |

**Comment by imsobear** [comment]
能想到的几个：

- `--analyzer`
- `--https`
- minify: true/false 即可
- dropLogLevel
- hash
- outputDir
- tsChecker
- eslint

**Comment by ClarkXia** [comment]
remoteRuntime 单独设计，其余能力已完善
