### ISSUE TITLE
对 esbuild/swc/unplugin 等关系的梳理

### ISSUE THREAD

**Issue by imsobear** [ice-lab/ice-next#98]
当下存在的问题：

- 代码复杂度较高，概念也比较多，阅读起来比较困难，这块需要好好设计下
- 后续一些新需求如何设计不是很清晰

我的一些想法：

- 我们存在两个大的 compile task
  - web bundle: 使用 webpack，用于编译打包 web bundle
  - server bundle: 使用 esbuild，用于编译打包 server bundle(esm 格式)
- Mock 文件的编译应该是独立的 compile task？
- 未来针对 Kraken、小程序之类的构建跟上述的 compile task 会是什么关系，并列还是从属于某一个？
- transform 能力，目前是基于 unplugin 的规范，目的是保证多种 compile task 可以复用，包含：
  - esbuild 自带的 transform，比如 ts 转换、js 语法转换（仅 server bundle）
  - webpack 自带的 transform，有吗？CSS Modules？（仅 web bundle）
  - ts & js 语法转换，基于 SWC（仅 web bundle）
  - 多端产物移除，基于啥？（两边都需要）
  - jsx+（两边都需要）
  - ...还可能有什么？
- 可以看到 transform 可能会针对不同的 compile task，这个信息是否应该声明在 transform 里，而不是 compile task 自己去过滤 
- web 和 server 是不同的 compile task，开发者引入某些牵扯语法转换的 webpack plugin，server 下无法生效怎么办？比如用 React 组件写 svg 那种

**Comment by ClarkXia** [comment]
### 关于 Task

Task 为编译的任务，目前主要基于 Webpack
- web 构建任务中包含 server 端执行，两者有严重依赖关系，不应该视为两个任务
- 多端场景下 Kraken、小程序之类的逻辑都是一个独立的 Task
- Mock 单独的运行时编译服务跟主要 Task 无关，其他逻辑类似预编译

### 关于 transform

webpack 没有自带的语法转化，所有处理依赖 loaders / plugins 生态
TODO
